name: CD (Staging 40.82.144.18)

on:
    workflow_dispatch:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup SSH key
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: |
                      ${{ secrets.SSH_KEY }}

            - name: Add server to known_hosts
              run: |
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Upload repository to server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  source: '.'
                  target: '~/autoseo'
                  strip_components: 0

            - name: Remote deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  script: |
                      set -e
                      cd ~/autoseo

                      # Ensure Docker installed
                      if ! command -v docker >/dev/null 2>&1; then
                        curl -fsSL https://get.docker.com | sh
                        sudo usermod -aG docker $USER || true
                      fi

                      # Ensure docker compose V2
                      if ! docker compose version >/dev/null 2>&1; then
                        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
                        mkdir -p $DOCKER_CONFIG/cli-plugins
                        curl -SL https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
                        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
                      fi

                      # Ensure .env exists on server (do not overwrite secrets)
                      if [ ! -f .env ]; then
                        if [ -f .env.example ]; then cp .env.example .env; fi
                      fi

                      # Build and start containers
                      docker compose pull || true
                      docker compose build
                      docker compose up -d

                      # Health checks
                      echo "Waiting for services..."
                      sleep 5
                      curl -sf http://localhost/health || curl -sf http://localhost:8000/health
                      # Alembic migrations
                      docker compose exec -T backend sh -lc "alembic upgrade head" || true
